### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by AzureArtomis** [OnyxdevSoftware/rogueEditor#3]
Ever since they fixed an issue with Classic mode, I havent been able to log in with the client

**Comment by OnyxdevSoftware** [comment]
Seems to work for me still.
Make sure you have the latest version of the program.

**Comment by OnyxdevSoftware** [comment]
Sometimes the game server lags, which can timeout the program.

**Comment by OnyxdevSoftware** [comment]
> Ever since they fixed an issue with Classic mode, I havent been able to log in with the client

Seems to work for me still.
Make sure you have the latest version of the program.
- Sometimes the their servers lag, which can cause the program to timeout.

**Comment by SasorizaTsugare** [comment]
Im having the same issue. Downloaded the program from the link in the readme. Been trying every couple hours for like 4 hours now. I redownloaded the file and confirmed the time stamps on the executable were the same.

**Comment by OnyxdevSoftware** [comment]
> Im having the same issue. Downloaded the program from the link in the readme. Been trying every couple hours for like 4 hours now. I redownloaded the file and confirmed the time stamps on the executable were the same.
> 
> EDIT: NVM, muscle memory was apparently messing with my password. Thankfully my browser kept the password saved. Dont know how I used the editor yesterday without issue.

Glad you got it figured out! :)

**Comment by BusterB3ar** [comment]
I'm having the same issue but I know for a fact I'm typing my info in correctly. Any thought? I get this msg | Incorrect login information/server down... try again!

**Comment by AzureArtomis** [comment]
I am Using v4 and still get that error no matter when or how many times I try, not sure what's going on

**Comment by OnyxdevSoftware** [comment]
> I am Using v4 and still get that error no matter when or how many times I try, not sure what's going on

Add me on Discord and i will debug the issue for you.

**Comment by AzureArtomis** [comment]
> I'm having the same issue but I know for a fact I'm typing my info in correctly. Any thought? I get this msg | Incorrect login information/server down... try again!

Onyx and I looked into this a bit, seems like it is something Client side that is blocking the traffic for the program. Could be something with your personal Network or Router. I will be doing more testing soon on that front

**Comment by OnyxdevSoftware** [comment]
> > I'm having the same issue but I know for a fact I'm typing my info in correctly. Any thought? I get this msg | Incorrect login information/server down... try again!
> 
> Onyx and I looked into this a bit, seems like it is something Client side that is blocking the traffic for the program. Could be something with your personal Network or Router. I will be doing more testing soon on that front

Verified to work when they switched to mobile data.
So it's most likely (some) routers that blocks the traffic, or your personal AV/Firewall blocking the requests on certain networks.

90% of people testing it have had no issues so far, so take a look at your network and see if it's blocking external requests from unsigned applications.

**Comment by OnyxdevSoftware** [comment]
> > I'm having the same issue but I know for a fact I'm typing my info in correctly. Any thought? I get this msg | Incorrect login information/server down... try again!
> 
> Onyx and I looked into this a bit, seems like it is something Client side that is blocking the traffic for the program. Could be something with your personal Network or Router. I will be doing more testing soon on that front
**_Not everyone is affected by this issue._**

Turns out it's cloudflare blocking requests due to a recent DDOS attack on Pokerogue's server.
Because of this, Ip's from certain locations seems to get blocked temporarely when sending external requests.
To bypass this, try using a mobile hotspot when editing your account for now or see if restarting the router helps with it.

I'll be updating the editor soon to make checks.

**Comment by OnyxdevSoftware** [comment]
> > > I'm having the same issue but I know for a fact I'm typing my info in correctly. Any thought? I get this msg | Incorrect login information/server down... try again!
> > 
> > 
> > Onyx and I looked into this a bit, seems like it is something Client side that is blocking the traffic for the program. Could be something with your personal Network or Router. I will be doing more testing soon on that front

 **_Not everyone is affected by this issue._** Turns out it's cloudflare blocking requests due to a recent DDOS attack on Pokerogue's server. Because of this, Ip's from certain locations seems to get blocked temporarely when sending external requests. To bypass this, try using a mobile hotspot when editing your account for now or see if restarting the router helps with it.

**A final option if nothing else works**
Create an account and run the program on replit.
[https://replit.com/](https://replit.com/)
It will serve as a proxy & let you run Python scripts without needing to install it on your own machine.
